pr:
  branches:
    include:
      - main
  paths:
    include:
      - .azure_pipelines_snp.yml
      - .snpcc_canary

trigger:
  branches:
    include:
      - main
      - "release/*"
    exclude:
      - "release/1.x"
      - "release/2.x"

schedules:
  - cron: "0 9-18/3 * * Mon-Fri"
    displayName: Regular build
    branches:
      include:
        - main
    always: true

jobs:
  - template: .azure-pipelines-templates/configure.yml

  - template: .azure-pipelines-templates/deploy_aci.yml

  - template: .azure-pipelines-templates/test_on_remote.yml
    parameters:
      job_name: test_snp
      display_name: "Test SNP"
      depends_on: deploy_aci
      run_on: $[ dependencies.deploy_aci.outputs['deploy_aci.ipAddresses'] ]
      host_private_key: $[ dependencies.deploy_aci.outputs['generate_ssh_key.hostPrivKey'] ]

  - job: cleanup_aci
    displayName: "Cleanup ACI"
    pool:
      vmImage: ubuntu-20.04
    dependsOn: test_snp
    condition: always()
    steps:
      - script: |
          echo -e "\Installing Azure CLI..."
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          az login --service-principal -u $(CCF_SNP_CI_APP_ID) -p $(CCF_SNP_CI_SERVICE_PRINCIPAL_PASSWORD) --tenant $(CCF_SNP_CI_TENANT)
          pip install azure-mgmt-resource azure-identity azure-mgmt-containerinstance
          echo -e "\nInstalled Azure CLI and logged in"
          echo -e "\nRemoving Azure Container Instance/s..."
          python3.8 scripts/azure_deployment/arm_template.py remove aci --subscription-id $(CCF_AZURE_SUBSCRIPTION_ID) --resource-group ccf-aci --aci-type dynamic-agent --deployment-name ci-$(Build.BuildNumber)
          echo -e "\nDone"
        env:
          CCF_SNP_CI_APP_ID: $(CCF_SNP_CI_APP_ID)
          CCF_SNP_CI_SERVICE_PRINCIPAL_PASSWORD: $(CCF_SNP_CI_SERVICE_PRINCIPAL_PASSWORD)
          CCF_SNP_CI_TENANT: $(CCF_SNP_CI_TENANT)
          CCF_AZURE_SUBSCRIPTION_ID: $(CCF_AZURE_SUBSCRIPTION_ID)
