pr:
  branches:
    include:
      - main
  paths:
    include:
      - .azure_pipelines_snpcc.yml
      - .snpcc_canary

trigger:
  branches:
    include:
      - main
      - "release/*"
    exclude:
      - "release/1.x"
      - "release/2.x"

schedules:
  - cron: "0 9-18/3 * * Mon-Fri"
    displayName: Regular build
    branches:
      include:
        - main
        - "release/*"
      exclude:
        - "release/1.x"
        - "release/2.x"
    always: true

jobs:

  - job: deploy_aci
    displayName: "Deploy ACI"
    pool:
      vmImage: ubuntu-20.04
    steps:
      - script: echo $(ccfSnpCiAppId)
      - script: echo $ccfSnpCiAppId
      - script: echo $(CCFSNPCIAPPID)
        env:
          CCFSNPCIAPPID: $(ccfSnpCiAppId)
      - script: echo $CCFSNPCIAPPID
        env:
          CCFSNPCIAPPID: $(ccfSnpCiAppId)
      - script: echo $(ccfSnpCiServicePrincipalPassword)
      - script: echo $ccfSnpCiServicePrincipalPassword
      - script: echo $(CCFSNPCISERVICEPRINCIPALPASSWORD)
        env:
          CCFSNPCISERVICEPRINCIPALPASSWORD: $(ccfSnpCiServicePrincipalPassword)
      - script: echo $CCFSNPCISERVICEPRINCIPALPASSWORD
        env:
          CCFSNPCISERVICEPRINCIPALPASSWORD: $(ccfSnpCiServicePrincipalPassword)
      - script: echo $(ccfSnpCiTenant)
      - script: echo $ccfSnpCiTenant
      - script: echo $(CCFSNPCITENANT)
        env:
          CCFSNPCITENANT: $(ccfSnpCiTenant)
      - script: echo $CCFSNPCITENANT
        env:
          CCFSNPCITENANT: $(ccfSnpCiTenant)
      - script: echo $(ccfAzureSubscriptionId)
      - script: echo $ccfAzureSubscriptionId
      - script: echo $(CCFAZURESUBSCRIPTIONID)
        env:
          CCFAZURESUBSCRIPTIONID: $(ccfAzureSubscriptionId)
      - script: echo $CCFAZURESUBSCRIPTIONID
        env:
          CCFAZURESUBSCRIPTIONID: $(ccfAzureSubscriptionId)
      # - script: curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
      # - script: az login --service-principal -u $CCFSNPCIAPPID -p $CCFSNPCISERVICEPRINCIPALPASSWORD --tenant $CCFSNPCITENANT
      #   env:
      #     CCFSNPCIAPPID: $(ccfSnpCiAppId)
      #     CCFSNPCISERVICEPRINCIPALPASSWORD: $(ccfSnpCiServicePrincipalPassword)
      #     CCFSNPCITENANT: $(ccfSnpCiTenant)
      # - script: pip install azure-mgmt-resource azure-identity
      # - script: ssh-keygen -t rsa -f /root/.ssh/id_rsa -N ""
      # - script: python3.8 scripts/deploy_snp_aci.py --subscription-id $CCFAZURESUBSCRIPTIONID --deployment-name $(Build.BuildNumber)
      #   env:
      #     CCFAZURESUBSCRIPTIONID: $(ccfAzureSubscriptionId)

  - template: .azure-pipelines-templates/configure.yml
    parameters:
      depends_on: deploy_aci

  - template: .azure-pipelines-templates/common.yml
    parameters:
      target: SNPCC
      env:
        pool: sev-snp-pool
      cmake_args: "-DCOMPILE_TARGET=snp -DCMAKE_BUILD_TYPE=Debug -DLVI_MITIGATIONS=OFF -DVERBOSE_LOGGING=ON"
      suffix: "Debug"
      artifact_name: "SNPCC_Debug"
      ctest_filter: '-LE "benchmark|perf|tlstest|vegeta|suite"'
      depends_on: configure
