jobs:
  - job: deploy_aci
    displayName: "Deploy ACI"
    pool:
      vmImage: ubuntu-20.04
    steps:
      - script: |
          set -ex
          ssh-keygen -t rsa -b 4096 -f ~/.ssh/id_rsa -N ""
          echo "##vso[task.setvariable variable=hostPubKey]`cat ~/.ssh/id_rsa.pub`"
          echo "##vso[task.setvariable variable=hostPrivKey;isOutput=true;issecret=true]`cat ~/.ssh/id_rsa | tr '\n' '?'`"
        name: generate_ssh_key

      - template: azure_cli.yml

      - script: |
          set -ex
          python3.8 scripts/azure_deployment/arm_template.py deploy aci --subscription-id $(CCF_AZURE_SUBSCRIPTION_ID) --resource-group ccf-aci --aci-type dynamic-agent --deployment-name ci-$(Build.BuildNumber) --aci-ssh-keys "$(generate_ssh_key.hostPubKey)" > ~/aci_ips
          echo "##vso[task.setvariable variable=ipAddresses;isOutput=true]`cat ~/aci_ips`"
        name: deploy_aci
        env:
          CCF_AZURE_SUBSCRIPTION_ID: $(CCF_AZURE_SUBSCRIPTION_ID)

      - script: |
          set -ex
          IFS='\n' read -ra IP_ADDR_LIST <<< "$(deploy_aci.ipAddresses)"
          for IP_ADDR in "${IP_ADDR_LIST[@]}"; do
            echo -e "Testing connection with $IP_ADDR"
            ssh agent@$IP_ADDR -o "StrictHostKeyChecking no" 'echo "Connected successfully"'
          done
        name: test_ssh_connection
