variables:
  ssh_key: ${{ parameters.ssh_key }}

steps:
  - script: |
      set -ex
      mkdir ~/.ssh
      echo $(ssh_key) | base64 -d > ~/.ssh/id_rsa
      sudo chmod 600 ~/.ssh/id_rsa
    name: setup_key
    displayName: "Install SSH Key from Deployment Step"
