steps:
  - ${{ if not(eq(parameters.ssh_target, '')) }}:
      - script: |
          ssh agent@${{ parameters.ssh_target }} '
          cd ${{ parameters.working_directory }}
          ${{ parameters.commands }}
          '
        displayName: ${{ parameters.display_name }}
        condition: ${{ parameters.ssh_condition }}

  - ${{ if eq(parameters.ssh_target, '') }}:
      - script: |
          ${{ parameters.commands }}
        displayName: ${{ parameters.display_name }}
        workingDirectory: ${{ parameters.working_directory }}
        condition: ${{ parameters.ssh_condition }}
        env: ${{ parameters.ssh_env }}
