steps:
  - ${{ if not(eq(variables['SSH_TARGET'], '')) }}:
      - script: |
          env > ssh_env
          scp ssh_env agent@@${{ parameters.ssh_target }}:~/.ssh/environment
          ssh agent@${{ parameters.ssh_target }} '
          cd ${{ parameters.workingDirectory }}
          ${{ parameters.script }}
          '
        displayName: ${{ parameters.displayName }}
        condition: ${{ parameters.condition }}

  - ${{ if eq(variables['SSH_TARGET'], '') }}:
      - script: |
          ${{ parameters.script }}
        displayName: ${{ parameters.displayName }}
        workingDirectory: ${{ parameters.workingDirectory }}
        env: ${{ parameters.env }}
        condition: ${{ parameters.condition }}
