steps:
  - ${{ if not(eq(parameters.ssh_target, '')) }}:
      - script: |
          env > ssh_env
          rsync ssh_env agent@${{ parameters.ssh_target }}:~/.ssh/environment
          ssh agent@${{ parameters.ssh_target }} '
          cd CCF/${{ parameters.working_directory }}
          ${{ parameters.commands }}
          '
        displayName: ${{ parameters.display_name }}
        condition: ${{ parameters.ssh_condition }}
        env: ${{ parameters.ssh_env }}

  - ${{ if eq(parameters.ssh_target, '') }}:
      - script: |
          ${{ parameters.commands }}
        displayName: ${{ parameters.display_name }}
        workingDirectory: ${{ parameters.working_directory }}
        condition: ${{ parameters.ssh_condition }}
        env: ${{ parameters.ssh_env }}
