steps:
  - ${{ if not(eq(variables['SSH_TARGET'], '')) }}:
      - script: |
          env > ssh_env
          scp ssh_env agent@@${{ parameters.ssh_target }}:~/.ssh/environment
          ssh agent@${{ parameters.ssh_target }} '
          cd ${{ parameters.working_dir }}
          ${{ parameters.commands }}
          '
        displayName: ${{ parameters.display_name }}

  - ${{ if eq(variables['SSH_TARGET'], '') }}:
      - script: |
          ${{ parameters.commands }}
        displayName: ${{ parameters.display_name }}
        workingDirectory: ${{ parameters.working_directory }}
        env: ${{ parameters.env }}
