variables:
  SSH_TARGET: ${{ parameters.ssh_target }}
  SSH_PASSWORD: ${{ parameters.ssh_password }}

steps:
  - script: |
      echo -e "\nSSH Target specified, creating and setting SSH key for this executor..."
      sudo apt-get install sshpass
      ssh-keygen -t rsa -f ~/.ssh/id_rsa -N ""
      sshpass -p $SSH_PASSWORD ssh-copy-id agent@$SSH_TARGET -o "StrictHostKeyChecking no"
      echo -e "\n Executor key successfully installed"
    displayName: "Setup SSH Connection"
