parameters:
  depends_on: ""
  condition: ""

jobs:
  - job: ${{ parameters.job_name }}
    displayName: ${{ parameters.display_name }}
    dependsOn: ${{ parameters.depends_on }}
    condition: ${{ parameters.condition }}
    pool:
      vmImage: ubuntu-20.04
    timeoutInMinutes: 120
    steps:
      - task: InstallSSHKey@0
        displayName: "Install an SSH key"
        inputs:
          knownHostsEntry: ${{ parameters.run_on }}
          sshKeySecureFile: "remote_private_key"

      - script: |
        hostname
        ssh agent@${{ parameters.run_on }} 'hostname'

      - task: SSH@0
          inputs:
            sshEndpoint: agent@${{ parameters.run_on }}
            runOptions: 'commands'
            commands: |
              echo "Hello world"
              hostname
            readyTimeout: '20000' # string. Required. SSH handshake timeout. Default: 20000.

